#! /bin/bash
NAME=$1
EDITOR=geany
EXTENSION=md
if [ -f $NAME.md ]; then
	$EDITOR index.$EXTENSION "$NAME.$EXTENSION"
else
  echo "File $NAME.$EXTENSION doesn't exist so I'm not going to do anything"
fi
