#! /bin/bash
EDITOR=geany
EXTENSION=md
NAME=$1
DATE=$(date +'%Y/%m/%d')
if [ ! -f index.md ]; then
	printf "# Documentation Index\n\n\n\n" > index.$EXTENSION
fi
if [ ! -f $NAME.md ]; then
	printf "# \n\n## Arguments\n\n## Return Value\n\n*Created: $DATE*  \n*Last Update: $DATE*" > $NAME.$EXTENSION
	$EDITOR index.$EXTENSION
	$EDITOR $NAME.$EXTENSION
else
	echo "File $NAME.md already exists - doing nothing"
fi
